source "https://rubygems.org"

gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-twitter", ">= 0"
gem "rake", ">= 0"
gem "rake", ">= 0"
gem "rake", ">= 0"
gem "rake", ">= 0"
gem "ruboty-cron", ">= 0"
gem "ruboty-cron", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"
gem "ruboty-kokodeikku", ">= 0"